### PR TITLE
Beholder: JSON output

### PR DESCRIPTION
**Pull request by finwe**
JSON output availability for Jyxo Beholder

### CODE REVIEW

**Comment by finwe** [comment]
Refactored outputs offer more variability when using Beholder inside framework presenters, controllers and/or response objects.

**Comment by kukulich** [comment]
Nice!

**Comment by finwe** [comment]
Thanks, no problem. Would you please care for a tag/release?

**Comment by kukulich** [comment]
Done. https://github.com/jyxo/php/releases/tag/5.0.0

**Comment by finwe** [comment]
Thanks!

**Pull request merged**
